package com.init.JocDausM.Model;

import java.io.Serializable;

import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.mongodb.lang.NonNull;

@Document(collection = "Jugador")
public class Jugador implements Serializable {

	// This is a global variable which replace the id generated by mongo specific
	// for each player
	@Transient
	public static final String SEQUENCE_NAME = "jugadors_sequence";

	@Id
	@NonNull
	private long id;

	@Field(name = "nom")
	private String nom;

	@Field(name = "date")
	@Temporal(TemporalType.TIMESTAMP)
	private java.util.Date data;

//	//@OneToMany(mappedBy="jugador", cascade = {CascadeType.ALL})
//	@JsonIgnore
//	private List<Tirada>llistaTirades;

	@Transient
	private Double porcentatgeExit;

	public Jugador() {
	}

	public Jugador(long id, String nom, java.util.Date data) {
		this.id = id;
		this.nom = nom;
		this.data = data;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public java.util.Date getData() {
		return data;
	}

	public void setData(java.util.Date data) {
		this.data = data;
	}

//	public List<Tirada> getTirades() {
//		return llistaTirades;
//	}
//
//	public void setTirades(List<Tirada> tirades) {
//		this.llistaTirades = tirades;
//	}

	public Double getPorcentatgeExit() {
		return porcentatgeExit;
	}

	public void setPorcentatgeExit(Double porcentatgeExit) {
		this.porcentatgeExit = porcentatgeExit;
	}

	@Override
	public String toString() {
		return "Jugador [id=" + id + ", nom=" + nom + ", data=" + data + ", porcentatgeExit=" + porcentatgeExit + "]";
	}

//
//	public void addTirada(Tirada laTirada) {
//		
//		if(llistaTirades==null) llistaTirades=new ArrayList<>();
//				
//		llistaTirades.add(laTirada);
//				
//		laTirada.setId_jugador(this.id);
//				
//				}

}
